// <auto-generated />
namespace Queue.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:Queue/Migrations/202402092045248_initialmigration.Designer.cs
    public sealed partial class initialmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202402092045248_initialmigration"; }
========
    public sealed partial class InitialMigrationNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialMigrationNew));
        
        string IMigrationMetadata.Id
        {
            get { return "202402191528522_Initial-Migration-New"; }
>>>>>>>> master:Queue/Migrations/202402191528522_Initial-Migration-New.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
